/* eslint-disable */
// This file is generated by scripts/build_pricing_catalog_ts.py
// Source: docs/pricing.extracted.json

import type { PricingExtracted } from './types';

export const pricingCatalog: PricingExtracted = {
  "sourcePdf": "Pricing Sheet- LifePrep Academy.pdf",
  "catalog": {
    "programOptions": [
      {
        "value": "position",
        "label": "Position Training"
      },
      {
        "value": "team_position",
        "label": "Team Position Training"
      },
      {
        "value": "team_strength",
        "label": "Team Strength Training"
      },
      {
        "value": "team_combination",
        "label": "Team Combination Training"
      },
      {
        "value": "combination",
        "label": "Combination Training"
      },
      {
        "value": "strength",
        "label": "Strength Training"
      }
    ],
    "frequencyOptions": [
      {
        "value": 1,
        "label": "1x / week"
      },
      {
        "value": 2,
        "label": "2x / week"
      },
      {
        "value": 3,
        "label": "3x / week"
      }
    ],
    "commitmentOptions": [
      {
        "value": 1,
        "label": "1 month"
      },
      {
        "value": 2,
        "label": "2 months"
      },
      {
        "value": 3,
        "label": "3 months"
      }
    ]
  },
  "programs": [
    {
      "programKey": "position",
      "programName": "Position Training",
      "currency": "usd",
      "isTeam": false,
      "dropInFeeCents": 4000,
      "prices": [
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 1,
          "amountCents": 14999
        },
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 2,
          "amountCents": 12499
        },
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 3,
          "amountCents": 9999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 1,
          "amountCents": 24999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 2,
          "amountCents": 19999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 3,
          "amountCents": 14999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 1,
          "amountCents": 29999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 2,
          "amountCents": 24999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 3,
          "amountCents": 19999
        }
      ]
    },
    {
      "programKey": "team_position",
      "programName": "Team Position Training",
      "currency": "usd",
      "isTeam": true,
      "teamMinPlayers": 8,
      "prices": [
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 1,
          "amountCents": 12499
        },
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 2,
          "amountCents": 9999
        },
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 3,
          "amountCents": 7499
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 1,
          "amountCents": 22499
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 2,
          "amountCents": 17499
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 3,
          "amountCents": 12499
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 1,
          "amountCents": 19999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 2,
          "amountCents": 14999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 3,
          "amountCents": 12499
        }
      ]
    },
    {
      "programKey": "team_strength",
      "programName": "Team Strength Training",
      "currency": "usd",
      "isTeam": true,
      "teamMinPlayers": 8,
      "prices": [
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 1,
          "amountCents": 12499
        },
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 2,
          "amountCents": 9999
        },
        {
          "frequencyPerWeek": 1,
          "commitmentMonths": 3,
          "amountCents": 7499
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 1,
          "amountCents": 22499
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 2,
          "amountCents": 17499
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 3,
          "amountCents": 12499
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 1,
          "amountCents": 19999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 2,
          "amountCents": 14999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 3,
          "amountCents": 12499
        }
      ]
    },
    {
      "programKey": "team_combination",
      "programName": "Team Combination Training",
      "currency": "usd",
      "isTeam": true,
      "teamMinPlayers": 8,
      "dropInFeeCents": 4000,
      "prices": [
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 1,
          "amountCents": 34999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 2,
          "amountCents": 24999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 3,
          "amountCents": 19999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 1,
          "amountCents": 44999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 2,
          "amountCents": 34999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 3,
          "amountCents": 24999
        }
      ]
    },
    {
      "programKey": "combination",
      "programName": "Combination Training",
      "currency": "usd",
      "isTeam": false,
      "dropInFeeCents": 4000,
      "prices": [
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 1,
          "amountCents": 39999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 2,
          "amountCents": 29999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 3,
          "amountCents": 24999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 1,
          "amountCents": 49999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 2,
          "amountCents": 39999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 3,
          "amountCents": 29999
        }
      ]
    },
    {
      "programKey": "strength",
      "programName": "Strength Training",
      "currency": "usd",
      "isTeam": false,
      "dropInFeeCents": 4000,
      "prices": [
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 1,
          "amountCents": 24999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 2,
          "amountCents": 19999
        },
        {
          "frequencyPerWeek": 2,
          "commitmentMonths": 3,
          "amountCents": 14999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 1,
          "amountCents": 29999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 2,
          "amountCents": 24999
        },
        {
          "frequencyPerWeek": 3,
          "commitmentMonths": 3,
          "amountCents": 19999
        }
      ]
    }
  ]
}
 as const;
