from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    src_json = repo_root / "docs" / "pricing.extracted.json"
    out_ts = repo_root / "packages" / "pricing" / "src" / "pricingCatalog.ts"

    if not src_json.exists():
        raise SystemExit(f"Missing input JSON: {src_json}")

    payload = json.loads(src_json.read_text(encoding="utf-8"))

    ts = """/* eslint-disable */
// This file is generated by scripts/build_pricing_catalog_ts.py
// Source: docs/pricing.extracted.json

import type { PricingExtracted } from './types';

export const pricingCatalog: PricingExtracted = """

    ts += json.dumps(payload, indent=2, ensure_ascii=False)
    ts += "\n as const;\n"

    out_ts.parent.mkdir(parents=True, exist_ok=True)
    out_ts.write_text(ts, encoding="utf-8")
    print(f"Wrote: {out_ts}")


if __name__ == "__main__":
    main()
